### ISSUE TITLE
Unify multiple tolerance combinations

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#10]
Currently, for AM vs BDF and JWS vs Biomodels, different tolerance combinations are considered, that should be unified. @paulstapor which one had we decided on?

**Comment by paulstapor** [comment]
Depends a bit how long this takes. Ir doesn't get easier by this:
We need the trajectory comparison for two things:
 1. Deciding, which models we want to accept
 2. Plotting Supplementary Figure 1
For both purposes, we have different tolerances again...

If the script are fast enough now, I would strongly suggest to unify also these...

**Comment by paulstapor** [comment]
Overall, I would suggest the following list:
 - `(atol, rtol) = (1.e-3, 1.e-3)`
 - `(atol, rtol) = (1.e-6, 1.e-3)`
 - `(atol, rtol) = (1.e-6, 1.e-6)`
 - `(atol, rtol) = (1.e-8, 1.e-6)`
 - `(atol, rtol) = (1.e-6, 1.e-8)`
 - `(atol, rtol) = (1.e-12, 1.e-10)`
 - `(atol, rtol) = (1.e-10, 1.e-12)`
 - `(atol, rtol) = (1.e-16, 1.e-8)`
 - `(atol, rtol) = (1.e-8, 1.e-16)`
 - `(atol, rtol) = (1.e-14, 1.e-14)`
This would be (I think) a reasonable list for the trajectory comparison, as
 - It covers all the tolerances we use in the "whole study" part
 - It covers all the tolerances we would like to plot in supplementary figure 1
That said: These are 10 tuples. Running them for the other setting combinations (2 * int algo, 2 * nonlinsol, 5 * linsol) leaves us with 200 settings to double check.
Now, everything depends a little on "how long do the simulations run"... Plus: Saving these thing for 447 models leaves us with 89,4k csv files in total... At this point, we should *really* think about switching to h5 files... leaving aus with 447 files with 200 datasets each, which is *much more* reasonable...
