### ISSUE TITLE
Regrouping of Python_Scripts

### ISSUE THREAD

**Issue by paulstapor** [yannikschaelte/solverstudy#18]
When everything is adapted, I'd like to finally create some subfolders in the Python_Scripts:
 - create_benchmark_collection (completely optional, download and regrouping of the models)
 - study_preparation (sbml import (amici and copasi) and trajectory comparison)
 - study_scripts (script which create the actual results)
 - plotting scripts (as the name says, but must work independently from all the upper things with the results we ship in this repo)

Opinions?

**Comment by yannikschaelte** [comment]
Definitely. Potentially
* Also discriminate between "Scripts" and "Src" purely functional code that is not called directly
* Rename "Python_Scripts" -> "Scripts" (I want to put bash scripts in there too ...)

**Comment by yannikschaelte** [comment]
On second thoughts, only _either_ split up as you said, _or_ into scripts and src. Renaming still.

**Comment by paulstapor** [comment]
Or just add `src` or `misc` to the model structure suggested.
however, the structure suggested above works by purpose (and is completely disjoint), not by api and hierarchy.
As we're not coding a toolbox, but a study, I would rather go for purpose than api.

**Comment by yannikschaelte** [comment]
Agreed!

**Comment by paulstapor** [comment]
Still a thing here? Or rather not?

**Comment by yannikschaelte** [comment]
Let's not change everything now anymore I'd say. Should be fine. Before a future project, one should tidy up naming and structure though.
