### ISSUE TITLE
In the end: rerun with current AMICI?

### ISSUE THREAD

**Issue by paulstapor** [yannikschaelte/solverstudy#19]
As the title goes...
Once we have reset up this whole thing: Makes sense to run the whole study and comparison using the newest Amici version? 
It should take roughly 1-2 days, but it could greatly improve the number of matching models...
Question is whether or not we want to plug it into the final study. However, we will want to rerun this for ourselves already, just to know and to double check how much we're better than Copasi, libroadrunner, or whatever other tool...
And how many more models we can (correctly) import by now...

**Comment by yannikschaelte** [comment]
I think it would not hurt, as we rerun most things anyway ... Scientifically, absolutely no problem to use a more up-to-date version of the packages, as we were requested to append the study anyway.

**Comment by yannikschaelte** [comment]
Short run-time estimate:

* Download of everything: 30 minutes
* AMICI compilation: 6h (Froehlich+Bigbones esp.) 
* Trajectory comparison: 2h (AMICI simulation 0.5h, but the comparison takes strangely long, can probably be optimized)
* Main study:
  * WholeStudy: 2-4 days (with 140 settings, 40 replicates)
  * ToleranceStudy: 2h (or more, don't remember ...)

I might not remember correctly, but this is very roughly.

**Comment by paulstapor** [comment]
> I think it would not hurt, as we rerun most things anyway ... Scientifically, absolutely no problem to use a more up-to-date version of the packages, as we were requested to append the study anyway.

Might also be reasonable, as number of correctly imported files etc. will change anyway...
If they change too drastically, we'll have a hard time explaining that... Even if we claim we used additional tolerances in the trajectory comparison for the bias assessment thing...
Saying we used a more up-to-date version of AMICI might be a good way out... :D

**Comment by paulstapor** [comment]
I think we now know, that this will not be realistic for the current study, although the code seems to be finished now. Closing this issue here. Will be interesting to run this again with more recent AMICI, possibly even including further solvers. But not right now. Closing.
