### ISSUE TITLE
Upload (to Cache?) Reference sedml+sbml files

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#26]

**Comment by paulstapor** [comment]
would now even suggest to upload the biomodels and the sedml folder... It's best, if the user hsa to rerun the "script_regroup_models.py", as this generates the model_summary table

**Comment by yannikschaelte** [comment]
agreed. ideally no downloads should be necessary thereafter.

**Comment by yannikschaelte** [comment]
Done.
