### ISSUE TITLE
Check trajectory comparison

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#4]
They rely on the assumption that the state orders coincide, which seems to be fulfilled, but should be made explicit.

In particular (sub-issue): Why does Froehlich fail after #2?

**Comment by paulstapor** [comment]
Would not be so sure that the state order must coincide, if the models are changed in an SED-ML.
I find it puzling that for almost every SED-ML, we have at least one matching SBML. But rarely more than one...
