### ISSUE TITLE
Check simulation definition

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#5]
Check that for AMICI and JWS (and COPASI if automatized) the same parameters are used.

**Comment by paulstapor** [comment]
Working on it.
The idea behind this should be: There is for each submodel of a benchmark model only one SBML file, which needs to further adaptation, be can be just simulated right away. Then, this simulation definition checking will be superfluous.

**Comment by yannikschaelte** [comment]
For JWS reference trajectories this remains, right? Either from the sedml or the post-sbml, the parameter values need to be read in and appended to the JWS query to obtain the reference trajectory.

**Comment by yannikschaelte** [comment]
Because: No 100% guarantee that the currently downloaded JWS reference trajectories are simulated with the right parameters. Probably yes thoguh.

**Comment by paulstapor** [comment]
Ah, okay! This was an important information I didn't have before! :+1:

**Comment by yannikschaelte** [comment]
Yes, probably better to check that too.

Btw: I can't make you co-owner (would need to move repo to icb-dcm first). If some rights are not missing, let me know. E.g. don't hesitate to merge things before tests passed (need 45min).

**Comment by yannikschaelte** [comment]
Now assuming the downloaded trajectories to be correct. Did a little check, seems to be all right.
