### ISSUE TITLE
Simplify state trajectory comparison

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#6]
Currently, nearly everything is duplicated for JWS and Biomodels, s.t. this should be easy to unify (-> less prone to errors).

**Comment by paulstapor** [comment]
Agreed. There should be one script, which covers both. We need to think a little about the architecture though:
 - One script for adapting SED-MLs to SBMLs
 - One script to run all simulaitons with AMICI (no matter if biomodels or JWS) -> saving trajectories as h5
 - One script to do so with COPASI -> saving trajectories as h5
 - One script which compares and creates one tsv file with: rows models, columns settings (including COPASI?), saving only "Success or failure"
