### ISSUE TITLE
Track variability in simulation times

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#7]
In SimAllSettings, we currently only report mean/median. Trivial to either add variance, or just report all 40 simulation times.

**Comment by paulstapor** [comment]
Meaning: 169 settings, times 200 models roughly, times 40 runs...
I opt for: 1 tsv file per settings combination, listing model names as indices, columns `num state var`, `num reactions`, `num parameters`, and then 40 columns with run times, right?
Should be okay to save...
