### ISSUE TITLE
Check "similar" Biomodels models

### ISSUE THREAD

**Issue by yannikschaelte** [yannikschaelte/solverstudy#8]
Some names are strikingly similar to JWS models

**Comment by paulstapor** [comment]
will check. Should be:
 * [x] Bungay2003
 * [x] Bungay2006
 * [x] Bungay2006a
 * [x] Leloup1999
 * [x] Levchenko200a
 * [x] Liu2011
 * [x] ODea2007

**Comment by paulstapor** [comment]
First check yielded:
 - The Bungay models are almost surely duplicates. There are 2 SED-MLs (2003 and 2006), and the 2006 ist split up into different sbmls, so there there two sbmls in Biomodels (Bungay2006 and Bungay2006a).
 - Levchenko is weird. the JWS and the Biomodels refer to the very same publication. However, the publication contains more than one model, and the number of state trajectories in the biomodels levchenko and the JWS levchenko is *very* different...
I now checked, whether maybe a lot of species are constant in the levchenko model and they aren't... So: We might want to keep both in this case, tagging them with an `a` or something similar
 - Leloup is fine, as the biomodels one can not even be imported. However, here we have 3 really different models in total (not even counting the biomodels one), out of which we can correctly simulate 2.
 - Liu is a duplicate as well, although things are very fishy: The description on JWS and Biomodels fit, but the ID on biomodels is not the one referenced on the JWS info part... :man_shrugging: I would remove the biomodels Liu model.
 - Also Odea is a duplicate. Again, let's remove the biomodels version.

I would suggest that we just remove the biomodels models, or compare the simulated timepoints or similar...
In any case: It makes sense to remove one model occurence, as we may get a biased result, depending on how the final cpu time is counted (i.e., averaged)
